In [2]:
import tensorflow as tf
import warnings
warnings.filterwarnings("ignore")

/Users/saurmoha/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/saurmoha/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/saurmoha/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/saurmoha/anaconda3/lib/python3.7/site-packages/tensorflow/python/f

In [3]:
print(tf.__version__)

2.0.0-beta0


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
 #/Users/saurmoha/Downloads/Churn_Modelling.csv 
dataset = pd.read_csv('/Users/saurmoha/Downloads/Churn_Modelling.csv')

In [6]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
x = dataset.drop(labels=['RowNumber','CustomerId','Surname','Exited'], axis=1)
y = dataset['Exited']

In [8]:
# Encoding the categorical data
from sklearn.preprocessing import LabelEncoder

In [9]:
label_1 = LabelEncoder()
x['Geography'] = label_1.fit_transform(x['Geography'])

In [10]:
x.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0  Female   42       2       0.00              1   
1          608          2  Female   41       1   83807.86              1   
2          502          0  Female   42       8  159660.80              3   
3          699          0  Female   39       1       0.00              2   
4          850          2  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [11]:
label_2 = LabelEncoder()
x['Gender'] = label_2.fit_transform(x['Gender'])

In [12]:
# Avoiding the Dummy variable trap
x = pd.get_dummies(x, drop_first=True, columns=['Geography'])

In [13]:
# Splitting the dataset into train and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [14]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [15]:
# Creating an object (Initilizing the ANN)
model = tf.keras.models.Sequential()

In [16]:
x_train

array([[ 0.16958176, -1.09168714, -0.46460796, ...,  1.10643166,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.91601335,  0.30102557, ..., -0.74866447,
         1.75486502, -0.57369368],
       [-1.19119591, -1.09168714, -0.94312892, ...,  1.48533467,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 ,  0.91601335, -0.36890377, ...,  1.41231994,
        -0.5698444 , -0.57369368],
       [-0.62420521, -1.09168714, -0.08179119, ...,  0.84432121,
        -0.5698444 ,  1.74309049],
       [-0.28401079, -1.09168714,  0.87525072, ...,  0.32472465,
         1.75486502, -0.57369368]])

In [17]:
x_test

array([[-0.55204276, -1.09168714, -0.36890377, ...,  1.61085707,
         1.75486502, -0.57369368],
       [-1.31490297, -1.09168714,  0.10961719, ...,  0.49587037,
        -0.5698444 , -0.57369368],
       [ 0.57162971, -1.09168714,  0.30102557, ..., -0.42478674,
        -0.5698444 ,  1.74309049],
       ...,
       [-0.74791227,  0.91601335, -0.27319958, ...,  0.71888467,
        -0.5698444 ,  1.74309049],
       [-0.00566991,  0.91601335, -0.46460796, ..., -1.54507805,
         1.75486502, -0.57369368],
       [-0.79945688,  0.91601335, -0.84742473, ...,  1.61255917,
         1.75486502, -0.57369368]])

# Building the model

In [18]:
model = tf.keras.models.Sequential()

In [19]:
# Adding input layer and first hidden layer
# 1) units = 6
# 2) activation function = ReLU
# 3) input dimention = 11
model.add(tf.keras.layers.Dense(units=6, activation='relu', input_dim = 11))

In [20]:
# Adding second hidden layer
model.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [21]:
# Output layer
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [22]:
# Compiling the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [23]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 72        
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


# Step 4: Training the model

In [24]:
model.fit(x_train, y_train.to_numpy(), batch_size=10, epochs=20)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 8000 samples
Epoch 1/20
8000/8000 [==============================] - 1s 111us/sample - loss: 0.5257 - accuracy: 0.7954
Epoch 2/20
8000/8000 [==============================] - 1s 100us/sample - loss: 0.4611 - accuracy: 0.7960
Epoch 3/20
8000/8000 [==============================] - 1s 99us/sample - loss: 0.4375 - accuracy: 0.7960
Epoch 4/20
8000/8000 [==============================] - 1s 95us/sample - loss: 0.4255 - accuracy: 0.7999
Epoch 5/20
8000/8000 [==============================] - 1s 92us/sample - loss: 0.4173 - accuracy: 0.8099
Epoch 6/20
8000/8000 [==============================] - 1s 97us/sample - loss: 0.4098 - accuracy: 0.8156
Epoch 7/20
8000/8000 [==============================] - 1s 97us/sample - loss: 0.4039 - accuracy: 0.8140
Epoch 8/20
8000/8000 [==============================] - 1s 97us/sample - loss: 0.3987 - accuracy: 0.8188
Epoch 9/20
8000/8000 [====================

# Evaluate the model

In [25]:
# Evaluate the model
test_loss, test_acc = model.evaluate(x_test, y_test.to_numpy())

2000/2000 [==============================] - 0s 41us/sample - loss: 0.3436 - accuracy: 0.8610


In [26]:
print('Test Accuracy: {}'.format(test_acc))

Test Accuracy: 0.8610000014305115


In [27]:
y_pred = model.predict_classes(x_test)

In [28]:
print(y_pred)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [29]:
print(y_test)

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64


In [30]:
y_test = y_test.to_numpy()

In [31]:
print(y_pred[11]), print(y_test[11])

[0]
0


(None, None)

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1537   58]
 [ 220  185]]


In [33]:
acc_cm = accuracy_score(y_test, y_pred)
print(acc_cm)

0.861
